### ISSUE TITLE
Method name

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/robson#1]
Hi @RobsonAbreu!

I'd like to suggest you to change the method [getIndex](https://github.com/univas-first-exam/robson/blob/master/asset/js/PayService.js#L27) to another one with semantic meaning to this project.

![image](https://cloud.githubusercontent.com/assets/5324414/10777736/acc5ad94-7d05-11e5-9f85-bcb8495a1d56.png)

**Comment by RobsonAbreu** [comment]
changed method

**Comment by edysegura** [comment]
Nice!!
